[project]
name = "pim1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
    "psycopg2-binary>=2.9.11",
    "python-decouple>=3.8",
    "sqlalchemy>=2.0.44",
    "tabulate>=0.9.0",
]
